###
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic admin admin

grant_type=client_credentials

> {%
    client.global.set("jmix_token", response.body.access_token);
%}

###
POST http://localhost:8180/realms/sample/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic jmix-app Hw8jX5bhLQ3Dn4E7EV04Knppk9iWOC9t

grant_type=password&scope=openid&username=johndoe&password=test

> {%
    client.global.set("jmix_token", response.body.access_token);
%}

###
GET http://localhost:8080/rest/entities/sb_User
Accept: application/json
Authorization: Bearer {{jmix_token}}

###
GET http://localhost:8080/rest/bpm/process/management/engine
Accept: application/json
Authorization: Bearer {{jmix_token}}
